# Generated by Django 2.0.3 on 2018-07-09 01:58

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCreationJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pid', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('exercise_id', models.PositiveIntegerField()),
                ('device_id', models.PositiveIntegerField()),
                ('video_file', models.CharField(max_length=1024)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_recording_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
